export const HomeConstat = {
  en: {
    forDoc: "For doctors",
    forPat: "For patients",
    resourcer: "Resources",
    FAQ: "FAQ",
    login: "Log in",
    sing: "Sing up",
    title: "Get a check-up or a prescription from your couch",
    service: "Services for you",
    showDoctor: "See a doctor",
    showCalendary: "Book an appointment",
    service: {
      id: "one",
      title: "Services for you",
      one: "Primary care",
      two: "Therapy",
      three: "Specialist visits",
    },
    us: {
      id: "two",
      title: "Get to know us",
      one: "About us",
      two: "Carrers",
      three: "Press",
    },
    resource: {
      id: "three",
      title: "Resources",
      one: "Blog",
      two: "Healt A-Z",
      three: "Health calculators",
    },
  },
  es: {
    forDoc: "Para doctores",
    forPat: "Para pacientes",
    resourcer: "Recursos",
    FAQ: "FAQ",
    login: "Ingresar",
    sing: "Registrarse",
    title: "Hazte un chequeo o una receta desde tu sofa",
    service: "Servicios para ti",
    showDoctor: "Ver a un doctor",
    showCalendary: "Programa un turno",
    service: {
      id: "one",
      title: "Servicios para usted",
      one: "Primeros auxilios",
      two: "Terapia",
      three: "Visitas de especialistas",
    },
    us: {
      id: "two",
      title: "Conózcanos",
      one: "Acerca de nosotros",
      two: "Carreras",
      three: "Prensa",
    },
    resource: {
      id: "three",
      title: "Recursos",
      one: "Blog",
      two: "Salud de la A-Z",
      three: "Visitas de especialistas",
    },
  },
};
